service: recombix-standups

# Provider

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"
  environment:
    # oauth token for the standups bot
    SLACK_OAUTH_TOKEN: ${env:SLACK_OAUTH_TOKEN}

# Plugins

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

# Functions

functions:
  standup_start: # Begin the standup flow at 9:30am
    handler: handlers/standup.start
    events:
      - schedule: cron(30 9 ? * MON-FRI *)
  standup_reminder: # Standup reminder at 9:50am
    handler: handlers/standup.reminder
    events:
      - schedule: cron(50 9 ? * MON-FRI *)
  standup_end: # Standup ends at 10:00 and posts messages
    handler: handlers/standup.end
    events:
      - schedule: cron(0 10 ? * MON-FRI *)
  slack_post: # This handles slack webhooks
    handler: handlers/slack.post
    events:
      - http:
          path: standups
          method: post
          cors: true
  add_user: # Currently we manually post here to add a user.
    handler: handlers/dev.add_user
    events:
      - http:
          path: users
          method: post
          cors: true

custom:
  dynamodb:
    start:
      migrate: true
  webpackIncludeModules: true

# CloudFormation resources

resources:
  Resources: # dynamodb users table and submissions table
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
    submissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: submissions
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
